[application]
# asset_dir = "assets" # The app no longer needs assets, as it uses hotlinking instead

[bundle]
identifier = "dev.pages.ahi"
publisher = "ahi"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "Auto≈°kola Testy"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
